# workflow name
name: CI-CD Pipeline

# trigger
on:
    push:
        branches:
        - main
      

# defines jobs
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v6
              with:
                python-version: "3.10"
            - name: Install Dependencies
              run: pip install -r requirements.txt
            
            - name: run test cases
              run: pytest --cov=calc --cov-report=term
            #   --cov-report=term: going to run coverage report into terminal


    deploy-job:
        runs-on: ubuntu-latest        
        needs: test-job
        steps:
            - name: print messsage
              run: echo "deploy job started..."
